# Generated by Django 4.2.6 on 2023-11-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('telefone', models.IntegerField()),
            ],
        ),
    ]
