# Generated by Django 4.2.6 on 2023-10-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
